apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-link-pedidocompra-contapagar-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-link-pedidocompra-contapagar-ms
  template:
    metadata:
      labels:
        app: md-link-pedidocompra-contapagar-ms
    spec:
      containers:
      - name: md-link-pedidocompra-contapagar-ms-container
        image: registry.digitalocean.com/oondemand/md-link-pedidocompra-contapagar-ms:0.0.5
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "1024Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: md-link-pedidocompra-contapagar-ms-service
spec:
  type: LoadBalancer
  selector:
    app: md-link-pedidocompra-contapagar-ms
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000